version: '3.9'

networks:
  salas-network:
    driver: bridge


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: frankstark/reserva-salas
    container_name: reserva-salas
    ports:
      - 8080:8080
    volumes:
      - ./dados:/app/dados
    networks:
      - salas-network

  prometheus:
    image: prom/prometheus
    restart: always
    container_name: salas-prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./prometheus/data:/prometheus
    ports:
      - 9090:9090
    networks:
      - salas-network
    

  grafana:
    image: grafana/grafana
    user: "1001:1001"
    container_name: salas-grafana
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - salas-network
    depends_on:
      - prometheus
