global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'salas-prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'reserva-salas'
    static_configs:
      - targets: ['reserva-salas:8080']
