name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Configura o repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura o Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22  # Alterar para sua versão do Go

    # Baixa dependências e verifica o código
    - name: Install Dependencies
      run: go mod tidy

    - name: Run Tests
      run: go test ./... -v

    # Análise de código com SonarQube
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # Configura o Docker
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/reserva-salas:${{ github.sha }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/reserva-salas:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/reserva-salas:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/reserva-salas:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/reserva-salas:latest
